name: Stock Daily Scanner

on:
  schedule:
    - cron: "0 11 * * *" # 한국시간 오후 8시
  workflow_dispatch: # 수동 실행 버튼

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 1. 기초 라이브러리 설치
          pip install pandas numpy pymongo finance-datareader yfinance
          # pykrx를 특정 안정 버전(1.0.45)으로 고정 설치하여 함수명 변경 이슈 차단
          pip install pykrx==1.0.45

      - name: Run scanner
        run: python scanner/main.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}